default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: backend_development


test:
  <<: *default
  database: backend_test