version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data
    networks:
    - internet
    - intranet
    
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
    - "27017:27017"
    networks:
    - intranet
    volumes:
    - database:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
    - "8081:8081"
    networks:
    - internet
    - intranet
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

  backend:
    #image:
    build: ./backend
    container_name: backend
    restart: always
    ports:
    - "2222:2222"
    networks:
    - internet
    - intranet
    depends_on:
    - mongo
  
  frontend:
    #image:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
    - "3000:3000"
    networks:
    - internet
    - intranet
    depends_on:
    - backend

volumes:
  portainer:
  database:

networks:
  intranet:
    internal: false
    driver: overlay
    name: intranet
    
  internet:
    name: internet